---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: argocd
spec:
  encryptedData:
    my-token: AgBH1Zpik3MA/sRwkFwBrX0U+LRJabDjEXX17ljmwKFJshmswavjfq6ltzRkkg+pmyc3NwoE/ol/3CvO4xD1Px81sb9pOBBEYZXmNQkDng0Wdg1Vmib7UmOyyU3LvsSy4eLOIZjPMme7V1SVQ0fwSzjxyCLlvGCFuixwy+krZV9MZbZieUhk2e8NrNTMedwCLgoa+jYgkPCFyrMD3E/CuFn5Su7938StP7+xJTJ7S0o2r+HtSltjuZC+wS+7teYNhSd4lIrB5CzTJ1QazF1oylau+svb091HWui8rP5bKXhGEEc2hvg82dj4OXKdaXVXJoydpf4c7rwzEqetKkhzavgnKtY/XKfeCywEmFUYi8P0gxc8dSOQwrUss4e5vw22iobuuhLK3VeoFF9HxHzhxlzNr1znFKZ1wSI1WqvQekiNG5LPWuEHBzRUMa3+/ahDp9pjVSWtUK/QiqvYd2p76gllyxjBy6YG96pjLQXEfzcUY3L0DEBVpB3dYrlh9CBHSWaP2pexVAnRSPjcFla9M+aWUkx1CRV9+GzmihrnWLwJwN7f4b0ZVLChPR6lvaVvMMPyXNxTAQBGSxnZSDrIS9h1yh9I1XL6LjiFhKl8zAUoXBqlOl0BALd5PMf1McQMvK0iPR3QjubBMM/3qR+PVSnxmls8sa/5zZ92l/eAX2BtAS5jnCdflsQYq+cuuOaeG9wOi8OvK7qUU11R1R5r93Y/VIBkVClhfHm+6QwpCcJvwSqRKhRjL9pN1cIeZw==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: argocd
    type: Opaque
